dataset_name : customers

source :
  format : parquet
  path : data/bronze/customers

destination:
  format : parquet
  path : data/silver/customers
  mode : overwrite

transformation:
  module : src.transformation.silver.customers
  function : transform

partition:
  enabled : false
  columns : []

quality:
  required_columns :
    - customer_id
    - customer_unique_id
    - customer_zip_code_prefix
    - customer_city
    - customer_state
  key_columns : 
    - customer_id