dataset_name : geolocation

source : 
  format : parquet
  path : data/bronze/geolocation

destination:
  format : parquet
  path : data/silver/geolocation
  mode : overwrite

transformation:
  module : src.transformation.silver.geolocation
  function : transform

partition:
  enabled : false
  columns : []

quality:
  required_columns :
    - geolocation_zip_code_prefix
    - geolocation_lat
    - geolocation_lng
    - geolocation_city
    - geolocation_state
  key_columns : []