dataset_name : order_payments

source:
  format : parquet
  path : data/bronze/order_payments

destination:
  format : parquet
  path : data/silver/order_payments
  mode : overwrite

transformation:
  module : src.transformation.silver.order_payments
  function : transform

partition:
  enabled : false
  columns : []

quality:
  required_columns :
  - order_id
  - payment_sequential
  - payment_type
  - payment_installments
  - payment_value
  key_columns : []