dataset_name : order_reviews

source : 
  format : parquet
  path : data/bronze/order_reviews

destination :
  format : parquet
  path : data/silver/order_reviews
  mode : overwrite

transformation:
  module: src.transformation.silver.order_reviews
  function : transform

partition:
  enabled : false
  columns : []

quality:
  required_columns :
    - review_id
    - order_id
    - review_score
    - review_comment_title
    - review_comment_message
    - review_creation_date
    - review_answer_timestamp
  key_columns : []