dataset_name : sellers

source : 
  format : parquet
  path : data/bronze/sellers

destination :
  format : parquet
  path : data/silver/sellers
  mode : overwrite

transformation:
  module: src.transformation.silver.sellers
  function : transform

partition:
  enabled : false
  columns : []

quality:
  required_columns :
    - seller_id
    - seller_zip_code_prefix
    - seller_city
    - seller_state
  key_columns : 
    - seller_id